name: CI

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
          cache: 'yarn'
      - run: yarn --frozen-lockfile
      - run: yarn run lint

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
          cache: 'yarn'
      - run: yarn --frozen-lockfile
      - run: yarn run build

  # Check that the build artifacts match those present in the dist dir
  check_artifacts_are_latest:
    needs: build

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
          cache: 'yarn'
      - run: yarn --frozen-lockfile
      - run: yarn run build && git diff --exit-code
