name: Pull Request - Check title

on:
  pull_request:
    branches:
      - main
      - dev/*.*.*
    # Only following types are handled by the action, but one can default to all as well
    types: [opened, reopened, edited, synchronize]

jobs:
  check-title:
    runs-on: ubuntu-latest

    # Ignore these cases
    # - Out of changelog target
    # - Created by "dependabot", "github-actions"
    if: >
      (
        !contains( github.event.pull_request.labels.*.name, 'flag/exclude-from-changelog' )
        && !startsWith( github.head_ref, 'dependabot/' )
        && !contains( github.actor, 'github-actions' )
      )
    steps:
      - uses: amannn/action-semantic-pull-request@v5.4.0
        with:
          types: |
            feat
            imprv
            fix
            support
            chore
            ci
            docs
            test
          requireScope: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
