name: Pull Request - Labelling

# repository Settings > Actions > General : Workflow permissions
permissions:
  pull-requests: write
on:
  pull_request:
    branches:
      - main
      - dev/*.*.*
    # Only following types are handled by the action, but one can default to all as well
    types: [opened, reopened, edited, synchronize]

jobs:
  # Refs: https://github.com/release-drafter/release-drafter
  labeling:
    runs-on: ubuntu-latest

    if: >
      !contains( github.event.pull_request.labels.*.name, 'flag/exclude-from-changelog' )

    steps:
      - uses: release-drafter/release-drafter@v5
        with:
          disable-releaser: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
